// <auto-generated />
using Backend_APIs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_APIs.Data.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20241029034147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Backend_APIs.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kids and Family"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Eco-Friendly Living"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Smart Home Technology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Back to School"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Others"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
